spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_platform_dev?useSSL=false&serverTimezone=UTC&characterEncoding=utf8mb4
    username: dev_user
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secretKey: "dev-very-long-secret-key-string-at-least-32-chars!"
  expirationSeconds: 3600
  tokenPrefix: "Bearer "
  header: "Authorization"

logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    com.courseplatform: DEBUG